.TH BESTFORTRESS 8 "Sun Aug 16 2009" "" "Network UPS Tools (NUT)"
.SH NAME
bestfortress \- Driver for old Best Fortress UPS equipment
.SH NOTE
This man page only documents the hardware-specific features of the
bestfortress driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports old Best Fortress UPS equipment.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in the
\fBups.conf\fR(5):

.IP "baudrate=\fInum\fR"
Set the speed of the serial connection - 1200, 2400, 4800 or 9600.

.IP "max_load=\fIVA\fR"
Set the value of the \fIups.load\fR variable.

.SH AUTHOR
Holger Dietze <holger.dietze@advis.de>,
Stuart D. Gathman <stuart@bmsi.com>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS The newer Best Power drivers:
\fBbestups\fR(8), \fBbestuferrups\fR(8), \fBbestfcom\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
