.TH bestuferrups 8 "Sun Jul 28 2002" "" "Network UPS Tools (NUT)"
.SH NAME
bestuferrups \- Driver for Best Power Micro\(hyFerrups
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
bestuferrups driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
Best Power Micro\(hyFerrups ME3100, probably other similar models too.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the    
\fBups.conf\fR(5).

.SH AUTHORS
Andreas Wrede, John Stone (bestuferrups)

Grant Taylor (bestfort)

Russell Kroll (bestups)

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
