.TH CYBERPOWER 8 "Tue Oct 15 2002" "" "Network UPS Tools (NUT)"
.SH NAME
cyberpower \- Serial Driver for most Cyber Power Systems UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
cyberpower driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports connections over a serial port for most AVR
models.  It was developed on the 700AVR, but has also been reported to
work on the 320AVR, 500AVR, 650AVR, 800AVR, 850AVR, 900AVR, 1250AVR,
and 1500AVR. 

The Power99 device is not supported by this driver (use the
\fBgenericups\fR driver instead). Also, CPS825VA, 1100AVR, and
1500AVR-HO are not supported (try the \fBpowerpanel\fR driver instead).

This driver does not support connections over a USB port. To connect
to a Cyber Power UPS over a USB port, use the \fBusbhid-ups\fR
driver. This has been reported to work for the 685AVR and possibly
other models.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the    
\fBups.conf\fR(5).

.SH BUGS

The protocol for this UPS is not officially documented.

Some variables may not be reported correctly on models other than those 
used by the developers.  This is partly due to the strange nonlinear 
relations between the reported values and their meanings on this hardware.

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
