.TH ETAPRO 8 "Tue Oct 22 2002" "" "Network UPS Tools (NUT)"
.SH NAME
etapro \- Driver for ETA UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
etapro driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports ETA UPS equipment with the "PRO" option for smart mode.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the
\fBups.conf\fR(5).

.SH AUTHOR
Marek Michalkiewicz <marekm@amelek.gda.pl>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
