.TH EVERUPS 8 "Wed Oct 16 2002" "" "Network UPS Tools (NUT)"
.SH NAME
everups \- Driver for Ever UPS models
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
everups driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver should recognize the NET *\(hyDPC and AP *\(hyPRO models.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the    
\fBups.conf\fR(5).

.SH BUGS

This UPS can only switch off the load if it's running on battery.  This
means you may be vulnerable to power races if your shutdown scripts
don't sleep and force a reboot.

.SH AUTHOR
Bartek Szady <bszx@bszxdomain.edu.eu.org>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
