.TH FENTONUPS 8 "Mon Jul 14 2003" "" "Network UPS Tools (NUT)" 
.SH NAME  
fentonups \- Driver for Fenton Technologies (Megatec protocol) UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
fentonups driver.  For information about the core driver, see  
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
.B fentonups 
primarily supports Fenton Technologies models such as the PowerPal,
PowerPure and PowerOn lines.  Due to the common heritage of UPS
equipment, it generally supports other hardware that also uses the 
Megatec protocol.

At the time of this writing, the PowerGuard PG\(hy600 and PowerCom SMK\(hy800A
are recognized and supported.  Other Megatec units should also work, but
they will generate a warning since their battery information is not known.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the    
\fBups.conf\fR(5).

.SH BUGS

The battery percentage is derived from the voltage data that the UPS
returns, since the UPS doesn't return that value directly.  On some
hardware, the charge will remain at 100% for a long time and then drops
quickly shortly before the battery runs out.  You can confirm from the
battery.voltage readings that this is a problem with the UPS and not
this driver.

Similarly, the float from the charger in some models forces the battery
charge percentage back up to 100% immedately after the UPS goes back
on\(hyline, so you can't tell when it is really recharged.

Dead/broken batteries can't be reported reliably.  If your UPS kills the 
load instantly or within seconds of starting the inverter, your batteries
probably need to be replaced.  Recently, a pair of 3.5 hour outages here
(thanks CPS!) finally killed my batteries.  You may have to run a manual
test from the front panel before the "replace battery" LED will light.

.SH AUTHOR
Russell Kroll

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
