.TH GAMATRONIC 8 "Thu Aug 4 2005" "" "Network UPS Tools (NUT)"
.SH NAME
gamatronic \- Driver for Gamatronic UPS equipment
.SH NOTE
This man page only documents the hardware-specific features of the
sec driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
Various - Rebuilt to work with Gamatronic UPS Units, but should recognize any UPS that speaks the SEC protocol at 1200-19200 bps.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the
\fBups.conf\fR(5).

.SH AUTHOR
Nadav Moskovitch <blutz@walla.com>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
