.TH ippon 8 "Wed Jul 14 2004" "" "Network UPS Tools (NUT)"
.SH NAME
ippon \- Driver for Ippon UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
ippon driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports Ippon UPS equipment.

.SH EXTRA ARGUMENTS

This driver supports the following optional settings in the
\fBups.conf\fR(5):

.IP "sdelay=num"

Specify delay of num minutes before switching off the load.

.IP "rdelay=num"

Specify delay of num minutes before restoring power (0 = never).

.SH AUTHOR
Alexander Fedorov <alexf@land.ru>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
