.TH IVTSCD 8 "Tue Sep 8 2009" "" "Network UPS Tools (NUT)"
.SH NAME
ivtscd \- driver for the IVT Solar Controller Device

.SH NOTE
This man page only documents the specific features of the
ivtscd driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH DESCRIPTION
This driver allows to access the IVT SCD-series devices.

.SH EXTRA ARGUMENTS
This driver does not support any extra argument.

.SH AUTHOR
Arjen de Korte <adkorte-guest@alioth.debian.org>

.SH SEE ALSO

\fBupscmd\fR(1),
\fBupsrw\fR(1),
\fBups.conf\fR(5),
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
