.TH liebert-esp2 8 "Fri Apr 09 2010" "" "Network UPS Tools (NUT)"
.SH NAME  
liebert-esp2 \- Driver for Liebert UPS, using the ESP2 serial protocol
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
liebert-esp2 driver.  For information about the core driver, see  
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This is an experimental driver.  You have been warned.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in \fBups.conf\fR(5):

.IP "baudrate=\fInum\fR"
Set the speed of the serial connection - 1200, 2400 (default), 4800, 9600 or 19200.

.SH AUTHOR
Richard Gregory <R.Gregory at liverpool.ac.uk>, Arjen de Korte <adkorte\(hyguest at alioth.debian.org>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
