.TH LIEBERT 8 "Wed Feb 18 2004" "" "Network UPS Tools (NUT)"
.SH NAME
liebert \- Driver for Liebert contact\(hyclosure UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
liebert driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports some Liebert UPS equipment with a contact\(hyclosure
interface.  This includes the UPStation GXT2 with their contact\(hyclosure
cable.  The smart mode ("Multilink") cable is not supported by this
driver.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the
\fBups.conf\fR(5).

.SH BUGS

This driver does not yet support shutdowns by raising DTR.  Be aware
that shutdowns are not possible with the stock contact\(hyclosure cable.
You may have to build another cable with DTR connected through to the
UPS for it to work.

There is no way for this driver to detect the hardware or cable.  It
will start up successfully even if no UPS is present.  This is a
fundamental limitation of any contact\(hyclosure driver.

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
