.TH MASTERGUARD 8 "Tue Apr  2 2002" "" "Network UPS Tools (NUT)"
.SH NAME
masterguard \- Driver for Masterguard UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
masterguard driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports Masterguard UPS equipment.

.SH EXTRA ARGUMENTS

.IP "CS"
Cancel the shutdown procedure.

.SH AUTHOR
Michael Spanier <mail@michael\(hyspanier.de>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
