.TH MEGATEC 8 "Sat Jan 14 2006" "" "Network UPS Tools (NUT)" 
.SH NAME  
megatec \- Driver for Megatec protocol based UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
megatec driver. For information about the core driver, see  
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
The megatec driver is known to work with the following UPSes:

    Maxxtro UPS 600VA
    Mustek PowerMust 400VA Plus
    Mustek PowerMust 600VA Plus
    Mustek PowerMust 800VA Pro
    Mustek PowerMust 1000VA Plus
    Mustek PowerMust 1400VA Plus
    Mustek PowerMust 2000VA USB
    OnLite AQUA 50
    Soyntec Sekury C 500
    Soyntec Sekury C 800
    Square One Power QP 1000
    Tecnoware Easy Power 1200
    Trust UPS 1000 Management PW-4105

It is also known to work with various models from Blazer, Energy Sistem
and Fenton Technologies. It may also work with similar models from other
manufacturers, but they haven't been tested.

On models with both a serial port (RS-232) and an USB port, only
the serial port is supported.

.SH EXTRA ARGUMENTS

.IP "mfr=\fIstring\fR"

Optional.  Specify the UPS manufacturer name.

.IP "model=\fIstring\fR"

Optional.  Specify the UPS model name.

.IP "serial=\fIstring\fR"

Optional.  Specify the UPS serial number.

.IP "lowbatt=\fIfloat\fR"

Optional.  Low battery level (%). Overrides the hardware default level.

.IP "ondelay=\fIint\fR"

Optional.  Delay before the UPS is turned back on (minutes).

.IP "offdelay=\fIint\fR"

Optional.  Delay before the UPS is turned off (minutes).

.SH UPS COMMANDS

This driver supports some extra commands (see \fBupscmd\fR(8)):

.IP beeper.toggle
Toggle the UPS beeper. (Not available on some hardware.)

.IP load.on
Turn on the load immediately.

.IP load.off
Turn off the load immediately.

.IP reset.input.minmax
Reset minimum and maximum input voltage status.

.IP reset.watchdog
Restarts the UPS watchdog timeout. The watchdog is started if it isn't running,
which means the UPS shuts down one minute after this command is executed for
the last time, restarting one minute afterwards. To cancel the watchdog, run
the "shutdown.stop" command.

.IP shutdown.return
Turn off the load and return when power is back.

.IP shutdown.stayoff
Turn off the load and remain off.

.IP shutdown.stop
Stop a shutdown in progress.

.IP test.battery.start.deep
Perform a long battery test (Not available on some hardware.)

.IP test.battery.start
Perform a (10 second) battery test.

.IP test.battery.stop
Stop a running battery test. (Not available on some hardware.)

.SH USER VARIABLES

The behavior of the driver can be controlled by some user definable
variables (see \fBupsrw\fR(8)):

.IP ups.delay.shutdown
Interval to wait after shutdown with delay command (seconds)

.IP ups.delay.start
Interval to wait before (re)starting the load (seconds)

.SH KNOWN PROBLEMS

The battery charge (%) value is only a best-effort calculation and may be
incorrect, or non-existant, for some UPS models.

Some UPS commands aren't supported by all models. In most cases, the driver
will send a message to the system log when the user tries to execute an
unsupported command. Unfortunately, some models don't even provide a way for
the driver to check for this, so the unsupported commands will silently fail.

Some models report a bogus value for the beeper status (will always be
"enabled" or "disabled"). So, the "beeper.toggle" command may appear to have no
effect in the status reported by the driver when, in fact, it is working fine.

The temperature value is also known to be bogus in some models.

.SH AUTHOR
Carlos Rodrigues <carlos.efr at mail.telepac.pt>

.SH SEE ALSO

\fBnutupsdrv\fR(8), \fBupsc\fR(8), \fBupscmd\fR(8), \fBupsrw\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
