.TH mustek 8 "Tue May  4 2004" "" "Network UPS Tools (NUT)"
.SH NAME
mustek \- Driver for Mustek UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
mustek driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports Mustek UPS equipment.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the
\fBups.conf\fR(5).

.SH AUTHOR
Martin Hajduch

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
