.TH HIDUPS 8 "Wed May 25 2005" "" "Network UPS Tools (NUT)"
.SH NAME
hidups \- Experimental Multi\(hyHID Driver for USB/HID UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
newhidups driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

This is an experimental driver.  Not all features may work correctly.

.SH SUPPORTED HARDWARE
.B newhidups
is an experiment to bring USB UPS monitoring to NUT on all platform
supporting USB through libusb. It should detect any UPS that uses
the HID power device class, but the amount of data will vary depending
on the manufacturer and model.

At the present time, newhidups only supports MGE UPS SYSTEMS models.

On Linux, you will need at least a 2.4.25 or 2.6.2 kernel
to disable hiddev support and avoid conflict. Otherwise,
prefer to use hidups driver.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in the 
\fBups.conf\fR(5) (or via the -x option):

.IP "offdelay=\fInum\fR"
Set the timer before the UPS is turned off after the kill power command is
sent (via the \fI\-k\fR switch).
The default value is 20 (in seconds), and MUST BE LOWER than ondelay.
 
.IP "ondelay=\fInum\fR"
Set the timer for the UPS to switch on in case the power returns after the
kill power command had been sent but before the actual switch off. This
ensures the machines connected to the UPS are, in all cases, rebooted after
a power failure.
The default value is 30 (in seconds), and MUST BE GREATER than offdelay.

.IP "vendor=\fIregex\fR"
.IP "product=\fIregex\fR"
.IP "serial=\fIregex\fR"
.IP "vendorid=\fIregex\fR"
.IP "productid=\fIregex\fR"

Select a specific UPS, in case there is more than one connected via
USB. Each option specifies an extended regular expression (see
\fIregex(7)\fR) that must match the UPS's entire vendor/product/serial
string (minus any surrounding whitespace), or the whole 4-digit
hexadecimal code for vendorid and productid. Try \fI-DD\fR for
finding out the strings to match. Examples: \fI-x vendor="APC.*"\fR,
\fI-x product=".*(Smart|Back)-?UPS.*"\fR.

.IP "bus=\fIregex\fR"

Select a UPS on a specific USB bus or group of busses. The argument is
a regular expression that must match the bus name where the UPS is
connected (e.g. bus="002", bus="00[2-3]"). 

.IP "generic"

With this option, the driver will connect to any device, including
ones that are not yet supported. This must always be combined with the
"vendorid" option. In this mode, the driver will not do anything
useful except for printing debugging information (typically used with
\fI-DD\fR).

.SH EXPERIMENTAL DRIVER
This driver has been tagged experimental, even if it has been reported
to be stable. Thus it is not suitable for production systems and it is
not built by default. This is mainly due to the fact that it is a
new driver, and that it will be replaced soon with a version using
an external HID library (libhid), as opposed to the current
internal ripped version.

.SH INSTALLATION
This driver is not built by default.  You can build it by using
"make usb", and install it using "make install\(hyusb". Note that
it will also install other USB drivers.
You also need to install manually the hotplug files (libhidups and
libhid.usermap), generally in etc/hotplug/usb/, to address the
permission settings problem. Lastly note that the libhidups file
must have execution flag set (ie using chmod +x ...).

.SH IMPLEMENTATION
newhidups only support 1 UPS at this time. You can put the
"auto" value for port in \fBups.conf\fR, i.e.:

.nf
	[newhidups]
		driver = newhidups
		port = auto
.fi

.SH KNOWN ISSUES AND BUGS
.SS "Got EPERM: Operation not permitted upon driver startup"

You have forgotten to install the hotplug files, as explained
in the INSTALLATION section above. Don't forget to restart
hotplug so that it applies these changes.

.SH AUTHORS
.SS Sponsored by MGE UPS SYSTEMS <http://opensource.mgeups.com/>
Arnaud Quette,
Peter Selinger

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
