.TH NITRAM 8 "Tue Oct 15 2002" "" "Network UPS Tools (NUT)"
.SH NAME
nitram \- Driver for Nitram Elite 2005 UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
nitram driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver was developed on the 500AVR. Other Nitram models may work too.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the
\fBups.conf\fR(5).

.SH BUGS

The protocol for this UPS is not officially documented.

.SH AUTHOR
Olivier and Nadine Albiez <oalbiez@free.fr>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
