.TH ONEAC 8 "Tue Oct 22 2002" "" "Network UPS Tools (NUT)"
.SH NAME
oneac \- Driver for Oneac UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
oneac driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports Oneac EG and ON UPS equipment with the
Advanced Interface. If your UPS is equipped with the Basic
Interface card, use the genericups driver.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in the
\fBups.conf\fR(5):

.IP "testtime=\fInum\fR"
Change battery test time from the 2 minute default.

.SH INSTANT COMMANDS
This driver supports the following Instant Commands.

.IP "reset.input.minmax"
Reset the minimum and maximum input line voltage values
seen since the last reset or power on.

.IP "test.battery.start"
Start a battery test.  The default time is 2 minutes.  This
time can be set in the ups.conf file.  See \fBtestime\fR above.

.IP "test.battery.stop"
Stops a battery test that is in progress.

.IP "test.failure.start"
Starts a 15 second long simulation of an input power
failure.

.SH AUTHOR
Eric Lawson <elawson@inficad.com>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
