.TH POWERCOM 8 "Fri Jan 25 2008" "" "Network UPS Tools (NUT)" 
.SH NAME  
powercom \- UPS driver for Powercom/Trust/Advice UPS equipment

.SH NOTE
This man page only documents the hardware\(hyspecific features of the
powercom driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver supports many similar kinds of UPS hardware.  The most common 
ones are the Trust 425/625, Powercom, and Advice Partner/King PR750.  
Others using the same protocol may also work.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in the 
\fBups.conf\fR(5):

.IP "linevoltage=\fIvalue\fR"
An integer specifying the mains voltage. It can't be auto detected. 
Acceptable values are in the range of 110\(hy120 or 220\(hy240. The default
is \fI230\fR.

.IP "manufacturer=\fIname\fR"
Specify the manufacturer name, which also can't be auto detected. This is 
a user defined string so any name is acceptable. The default is 
\fIPowerCom\fR.

.IP "modelname=\fIname\fR"
Specify the model name, which also can't be auto detected. This is a 
user defined string so any name is acceptable. The default is 
\fIUnknown\fR.

.IP "serialnumber=\fIvalue\fR"
Like modelname above, but for the serial number. The default is 
\fIUnknown\fR.

.IP "type=\fIname\fR"
The exact type of the communication protocol within the powercom family, 
that will be used to communicate with the UPS. The type is named after 
the first modelname that was coded with that protocol. The acceptable 
names are KP625AP, Trust, Egys, KIN, BNT, IMP and BNT-other. The default is 
\fITrust\fR.
\fIBNT-other\fR - it's a special type for BNT 100-120V models
for this type you can (I think must!) specify voltage, batteryPercentage, 
loadPercentage and validationSequence.

.IP "numOfBytesFromUPS=\fIvalue\fR"
The number of bytes in a UPS frame. The default is type dependant and 
is given below.

.IP "methodOfFlowControl=\fIname\fR"
The method of serial communication flow control that is engaged by the 
UPS. The default is type dependant and is given below. Acceptable names 
are dtr0rts1, dtr1 or no_flow_control.

.IP "shutdownArguments=\fI{{minutes,seconds},whether_minutes_should_be_used}\fR"
The minutes and seconds that the UPS should wait between receiving the 
shutdown command and actually shutting off. The other argument should 
be set to the character \fIn\fR only when the minutes value should be 
skipped and not sent to the UPS. The default is type dependant and is 
given below. The braces and commas are mandatory. Note that there should 
be no white space characters.

.IP "voltage=\fI{coefficient1,coefficient2,coefficient3,coefficient4}\fR"
Only for KP625AP, Trust, Egys, BNT-other
A quad that is used convert the raw data to human readable voltage 
reading. The default is type dependant and is given below. Do note that 
the braces and commas are mandatory, as well as the lack of white space
characters.

.IP "frequency=\fI{coefficient1,coefficient2}\fR"
Only for KP625AP, Trust, Egys
A pair to convert the raw data to human readable frequency reading. The 
default is type dependant and is given below. Do note that the braces 
and commas are mandatory as well, as the lack of white space characters.

.IP "batteryPercentage=\fI{coefficient1,coefficient2,coefficient3,coefficient4,coefficient5}\fR"
Only for KP625AP, Trust, Egys, BNT-other
A 5 tuple to convert the raw data to human readable battery percentage 
reading. The default is type dependant and is given below. Do note that 
the braces and commas are mandatory, as the lack of white space 
characters.

.IP "loadPercentage=\fI{coefficient1,coefficient2,coefficient3,coefficient4}\fR"
Only for KP625AP, Trust, Egys, BNT-other
A quad to convert the raw data to human readable load percentage 
reading. The default is type dependant and is given below. Do note that 
the braces and commas are mandatory, as the lack of white space 
characters.

.IP "validationSequence=\fI{{index1,value1},{index2,value2},{index3,value3}}\fR"
Only for KP625AP, Trust, Egys, BNT-other
3 pairs to be used for validating the UPS by comparing bytes of the raw 
data with constant values. The default is type dependant and is given 
below. The braces and commas are mandatory, as the lack of white space
characters.

.SH DEFAULT VALUES FOR THE EXTRA ARGUMENTS
.IP "linevoltage = \fI230\fR"
.IP "manufacturer = \fIPowerCom\fR"
.IP "modelname = \fIUnknown\fR"
.IP "serialnumber = \fIUnknown\fR"
.IP "type = \fITrust\fR"

.P 
The rest of the default values for the extra arguments are type 
dependant:

.IP "Trust"
.RS
.IP "numOfBytesFromUPS = 11"
.IP "methodOfFlowControl = dtr0rts1"
.IP "validationSequence = {{5,0},{7,0},{8,0}}"
.IP "shutdownArguments = {{0,10},n}"
.IP "frequency = {0.00020997,0.00020928}"
.IP "loadPercentage = {6.1343,\-0.3808,4.3110,0.1811}"
.IP "batteryPercentage = {5.0000,0.3268,\-825.00,4.5639,\-835.82}"
.IP "voltage = {1.9216,\-0.0977,0.9545,0.0000}"
.RE

.IP "KP625AP"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = dtr0rts1"
.IP "validationSequence = {{5,0x80},{7,0},{8,0}}"
.IP "shutdownArguments = {{0,10},n}"
.IP "frequency = {0.00020997,0.00020928}"
.IP "loadPercentage = {6.1343,\-0.3808,4.3110,0.1811}"
.IP "batteryPercentage = {5.0000,0.3268,\-825.00,4.5639,\-835.82}"
.IP "voltage = {1.9216,\-0.0977,0.9545,0.0000}"
.RE

.IP "Egys"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = no_flow_control"
.IP "validationSequence = {{5,0x80},{7,0},{8,0}}"
.IP "shutdownArguments = {{0,10},n}"
.IP "frequency = {0.00020997,0.00020928}"
.IP "loadPercentage = {6.1343,\-0.3808,1.3333,0.6667}"
.IP "batteryPercentage = {5.0000,0.3268,\-825.00,2.2105,\-355.37}"
.IP "voltage = {1.9216,\-0.0977,0.9545,0.0000}"
.RE

.IP "IMP"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = no_flow_control"
.IP "validationSequence = {{5,0xFF},{7,0},{8,0}}"
.IP "shutdownArguments = {{1,30},y}"
.RE

.IP "KIN"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = no_flow_control"
.IP "validationSequence = {{11,0x4b},{8,0},{8,0}}"
.IP "shutdownArguments = {{1,30},y}"
.RE

.IP "BNT"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = no_flow_control"
.IP "validationSequence = {{11,0x42},{8,0},{8,0}}"
.IP "shutdownArguments = {{1,30},y}"
.RE

.IP "BNT-other"
.RS
.IP "numOfBytesFromUPS = 16"
.IP "methodOfFlowControl = no_flow_control"
.IP "validationSequence = {{8,0},{8,0},{8,0}}"
.IP "shutdownArguments = {{1,30},y}"
.IP "loadPercentage = {1.4474,0.0,0.8594,0.0}"
.IP "batteryPercentage = {5.0000,0.3268,\-825.00,0.46511,0}"
.IP "voltage = {1.9216,\-0.0977,0.82857,0.0000}"
.RE

.SH AUTHOR
Peter Bieringer <pb@bieringer.de>
Alexey Sidorov <alexsid@altlinux.org>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
