.TH POWERMUST 8 "Fri May 14 2004" "" "Network UPS Tools (NUT)" 
.SH NAME  
powermust \(hy Driver for Mustek PowerMust series UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
powermust driver. For information about the core driver, see  
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
The powermust driver is known to work with the following UPSes:

    Maxxtro UPS 600VA
    Mustek PowerMust 400VA Plus
    Mustek PowerMust 600VA Plus
    Mustek PowerMust 800VA Pro
    Mustek PowerMust 1000VA Plus
    Mustek PowerMust 1400VA Plus
    Mustek PowerMust 2000VA USB
    OnLite AQUA 50
    Soyntec Sekury C 500
    Soyntec Sekury C 800
    Square One Power QP 1000
    Tecnoware Easy Power 1200
    Trust UPS 1000 Management PW-4105

It is also known to work with various models from Blazer, Energy Sistem
and Fenton Technologies. It may also work with similar models from
other manufacturers, but they haven't been tested.

.SH EXTRA ARGUMENTS

This driver does not support any extra settings in the    
\fBups.conf\fR(5).

.SH UPS COMMANDS

This driver supports some extra commands (see \fBupscmd\fR(8)):

.IP shutdown.return
Turn off the load and return when power is back

.IP shutdown.stayoff
Turn off the load and remain off

.IP shutdown.stop
Stop a shutdown in progress

.IP load.on
Turn on the load immediately

.IP load.off
Turn off the load immediately

.IP reset.input.minmax
Reset minimum and maximum input voltage status

.SH USER VARIABLES

The behavior of the driver can be controlled by some user definable
variables (see \fBupsrw\fR(8)):

.IP ups.delay.shutdown
Interval to wait after shutdown with delay command (seconds)

.IP ups.delay.start
Interval to wait before (re)starting the load (seconds)

.SH BUGS

No known bugs at the moment.

.SH AUTHOR
Carlos Rodrigues <carlos.efr@mail.telepac.pt>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
