.TH RHINO 8 "Wed Nov 30 2005" "" "Network UPS Tools (NUT)"
.SH NAME
rhino \- Driver for Brazilian Microsol RHINO UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
rhino driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver has been tested with :
  

Rhino   6000 VA

Rhino   7500 VA

Rhino  10000 VA

Rhino  20000 VA

All Rhino models are senoidal on\(hyline 

.SH EXTRA ARGUMENTS

This driver support the following extra optional settings in the
\fBups.conf\fR(5). \fR

\fBbattext = n\fR \(hy (default = 0, no extra battery, where n = Ampere*hour )

.SH UPSCMD


load.on  \(hy Turn on the load immediately

load.off \(hy Turn off the load immediately

bypass.start \(hy Put the UPS in bypass mode

bypass.stop  \(hy Put the UPS out of bypass mode

shutdown.stayoff \(hy Shut down in 3 minutes and do not return


.SH AUTHOR
Silvino B. Magalh\[~a]es <sbm2yk@gmail.com>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
