.TH RICHCOMM_USB 8 "Sat Dec 27 2008" "" "Network UPS Tools (NUT)"
.SH NAME
richcomm_usb \- Driver UPS equipment using Richcomm dry\(hycontact to USB
solution

.SH NOTE
This man page only documents the specific features of the richcomm_usb 
driver.  For information about the core driver, see \fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
The Richcomm dry\(hycontact to USB solution is a generic interface that is
used to upgrade an existing (RS-232) contact closure UPS interface to USB.
As such, all the limitations of the underlying contact closure interface
apply.  This means that you will only get the essentials in ups.status: OL,
OB, and LB.  See also \fBgenericups\fR(8).

.SH BUGS
Most contact\(hyclosure UPSes will not power down the load if the line power 
is present.  This can create a race when using slave \fBupsmon\fR(8) 
systems.  See the \fBupsmon\fR(8) man page for more information.

The solution to both of these problems is to upgrade to a smart protocol 
UPS of some kind that allows detection and proper load cycling on command.

.SH AUTHORS
Peter van Valderen <p.v.valderen at probu.nl>
Dirk Teurlings <dirk at upexia.nl>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
