.TH snmp\-ups 8 "Wed Nov 26 2008" "" "Network UPS Tools (NUT)"
.SH NAME
snmp\(hyups \- Multi\(hyMIB Driver for SNMP UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
snmp\(hyups driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
The snmp\(hyups driver automatically detects and supports a wide range of devices by loading various MIBS:
.IP "ietf:"
UPS that is RFC 1628 (UPS MIB) compliant, ie MGE UPS SYSTEMS, Liebert, perhaps others (default)
.IP "mge:"
MGE UPS SYSTEMS and MGE Office Protection Systems devices with SNMP cards (ref 66062, 66045, 66074 and 66244)
.IP "apcc:"
APC AP9606 APC Web/SNMP management card, perhaps others
.IP "netvision:"
Socomec Sicon UPS with Netvision Web/SNMP management card/external box
.IP "pw:"
Powerware devices with ConnectUPS SNMP cards
.IP "aphel_genesisII:"
Eaton Powerware ePDU Monitored
.IP "aphel_revelation:"
Eaton Powerware ePDU Managed
.IP "raritan:"
Various Raritan PDUs

.SH EXTRA ARGUMENTS

This driver supports the following optional settings in the
\fBups.conf\fR(5):

.IP "mibs=\fIname\fR"
Set MIB compliance (default=auto, allowed ietf,mge,apcc,netvision,pw,aphel_genesisII,aphel_revelation, raritan).
With auto the driver will try a select set of objets untill it finds one
that the device responds to.

.IP "community=\fIname\fR"
Set community name (default = public).
Note that you require a RW community name to perform UPS settings (as for a powerdown).

.IP "snmp_version=\fIversion\fR"
Set SNMP version (default = v1, the other allowed value is v2c)

.IP "pollfreq=\fIvalue\fR"
Set polling frequency in seconds, to reduce network flow (default=30)

.IP "notransferoids"
Disable the monitoring of the low and high voltage transfer OIDs in
the hardware.  This will remove input.transfer.low and input.transfer.high
from the list of variables.  This should only be used on APCC Symmetra
equipment which has strangeness in the three\(hyphase power reporting.

.SH REQUIREMENTS
You will need to install the Net\(hySNMP package from 
http://www.net\(hysnmp.org/ before building this driver.

.SH EXPERIMENTAL DRIVER
This driver has been tagged experimental, even if it has been reported
to be stable. Thus it may not be suitable for production systems and it is
only built if the Net SNMP development files are present on the system.
This is mainly due to the fact that there is still
no proper upsdrv_shutdown() function implemented. There probably never
will be one, since at the time this script should run (near the end of
the system halt script), there will be no network capabilities anymore.
Probably the only way to shutdown an SNMP UPS is by sending it a shutdown
with delay command through \fBupscmd\fR(8) and hope for the best that the
system will have finished shutting down before the power is cut.

.SH INSTALLATION
This driver is only built if the Net SNMP development files are present on the system.
You can also force it to be built by using "configure \-\-with\-snmp=yes" before calling make.

.SH IMPLEMENTATION
The hostname of the UPS is specified with the "port" value in
\fBups.conf\fR, i.e.:

.nf
	[snmp]
		driver = snmp\-ups
		port = snmp\-ups.example.com
		community = public
		snmp_version = v1
		mibs = ietf
		pollfreq = 15
.fi

.SH AUTHORS
.SS Sponsored by MGE UPS SYSTEMS <http://opensource.mgeups.com/>
Arnaud Quette, Dmitry Frolov

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS NUT SNMP Protocols Library
Available at: http://random.networkupstools.org/protocols/snmp/

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
