.TH SOLIS 8 "Wed Apr 13 2005" "" "Network UPS Tools (NUT)"
.SH NAME
solis \- Driver for Brazilian Microsol SOLIS UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
solis driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver has been tested with :
  

Solis   1000 VA

Solis   1500 VA

Solis   2000 VA

Solis   3000 VA

All Solis models are senoidal on\(hyline 

.SH EXTRA ARGUMENTS

This driver support the following extra optional settings in the
\fBups.conf\fR(5). \fR

\fBbattext = n\fR \(hy (default = 0, no extra battery, where n = Ampere*hour )

\fBprgshut = 1\fR \(hy (default = 0, no programable shutdown )

.SH UPSCMD


shutdown.return \(hy Shut down in .3 minutes and restart in .3 minutes

shutdown.stayoff \(hy Shut down in .3 minutes and do not return


.SH AUTHOR
Silvino B. Magalh\[~a]es <sbm2yk@gmail.com>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
