.TH TRIPPLITE 8 "Sat Aug 21 2004" "" "Network UPS Tools (NUT)"
.SH NAME
tripplite \- Driver for Tripp\(hyLite SmartPro UPS equipment
.SH NOTE
This man page only documents the hardware\(hyspecific features of the
tripplite driver.  For information about the core driver, see
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
This driver should work on the SmartPro line, including the SMART700
and SMART700SER.  It only supports SmartPro models that communicate
using the serial port.

.SH EXTRA ARGUMENTS
This driver supports the following optional settings in the 
\fBups.conf\fR(5):

.IP "offdelay=\fInum\fR"
Time to wait before the UPS is turned off after the kill power command is
sent.
The default value is 64 (in seconds).

.IP "rebootdelay=\fInum\fR"
Set the timer before the UPS is cycled after the reboot command is sent.
The default value is 64 (in seconds).

.IP "startdelay=\fInum\fR"
Set the time that the UPS waits before it turns itself back on after a
reboot command.
The default value is 60 (in seconds).

.SH KNOWN ISSUES AND BUGS
Battery charge information may not be correct for all UPSes.  It is tuned
to be correct for a SMART700SER.  Other models may not provide correct
information.  Information from the manufacturer would be helpful.

.SH AUTHORS
Rickard E. (Rik) Faith <faith@alephnull.com>
Nicholas Kain <nicholas@kain.us>

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
