.TH UPSCLI_STRERROR 3 "Mon Jan 22 2007" "" "Network UPS Tools (NUT)"
.SH NAME
upscli_strerror \- return string describing error condition
.SH SYNOPSIS
.nf
.B #include <upsclient.h>
.sp
.BI "char *upscli_strerror(UPSCONN *ups);"
.fi
.SH DESCRIPTION
The \fBupscli_strerror()\fP function takes the pointer \fIups\fP to a
UPSCONN state structure and returns a string describing the last error
which occurred on this connection.  The string is valid until the next
call to \fBupscli_strerror()\fP.
.SH "RETURN VALUE"
The \fBupscli_strerror()\fP function returns a description of the error,
or an unknown error message if the error code is not recognized.
.SH "SEE ALSO"
.BR upscli_fd "(3), "upscli_get "(3), "
.BR upscli_readline "(3), "upscli_sendline "(3), "
.BR upscli_ssl "(3), "
.BR upscli_strerror "(3), "upscli_upserror "(3) "
