.TH UPSD.CONF 5 "Mon Jan 22 2007" "" "Network UPS Tools (NUT)"
.SH NAME
upsd.conf \- Configuration for Network UPS Tools upsd

.SH DESCRIPTION

upsd uses this file to control access to the server and set some other
miscellaneous configuration values.  This file contains details on
access controls, so keep it secure.  Ideally, only the upsd process
should be able to read it.

.SH CONFIGURATION DIRECTIVES

.IP "MAXAGE \fIseconds\fR"

upsd usually allows a driver to stop responding for up to 15 seconds
before declaring the data "stale".  If your driver takes a very long
time to process updates but is otherwise operational, you can use MAXAGE
to make upsd wait longer.

Most users should leave this at the default value.

.IP "STATEPATH \fIpath\fR"

Tell upsd to look for the driver state sockets in \fIpath\fR rather
than the default that was compiled into the program.

.IP "LISTEN \fIinterface\fR \fIport\fR"

Bind a listening port to the interface specified by its Internet
address.  This may be useful on hosts with multiple interfaces.
You should not rely exclusively on this for security, as it can be
subverted on many systems.

Listen on TCP port \fIport\fR instead of the default value which was
compiled into the code.  This overrides any value you may have set
with 'configure \-\-with\-port'.  If you don't change it with configure
or this value, upsd will listen on port 3493 for this interface.

Multiple LISTEN addresses may be specified.  The default is to bind to
127.0.0.1 if no LISTEN addresses are specified (and ::1 if IPv6 support is
compiled in).

.IP
.nf
	LISTEN 127.0.0.1
	LISTEN 192.168.50.1
	LISTEN ::1
	LISTEN 2001:0db8:1234:08d3:1319:8a2e:0370:7344
.fi
.LP

This parameter will only be read at startup.  You'll need to restart
(rather than reload) upsd to apply any changes made here.

.SH SEE ALSO
\fBupsd\fR(8), \fBnutupsdrv\fR(8), \fBupsd.users\fR(5)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
