.TH VICTRONUPS 8 "Wed Oct 16 2002" "" "Network UPS Tools (NUT)" 
.SH NAME  
victronups \- Driver for IMV/Victron UPS unit Match, Match Lite, NetUps
.SH NOTE
This man page only documents the hardware\(hyspecific features of the the
victronups driver.  For information about the core driver, see  
\fBnutupsdrv\fR(8).

.SH SUPPORTED HARDWARE
victronups should recognize all Victron models that use a serial protocol at 
1200 bps.  These include Match Lite, Match and the NetUps line.

The Match Lite line may only report a handful of variables.  This is
usually not a bug \(hy they just don't support anything else.

.SH CABLING

If your Victron cable is broken or missing, use this diagram to build
a clone:

docs/cables/victron.txt

.SH EXTRA ARGUMENTS
This driver supports the following optional setting in the
\fBups.conf\fR(5):

.IP "modelname=<name>"
Set model name

.IP "usd=\fIdelay\fR"
Set delay before shutdown on UPS


.SH BUGS
The protocol for this UPS is not officially documented.

.SH AUTHOR
Radek Benedikt <benedikt@lphard.cz>,
Daniel Prynych <Daniel.Prynych@hornet.cz

.SH SEE ALSO

.SS The core driver:
\fBnutupsdrv\fR(8)

.SS Internet resources:
The NUT (Network UPS Tools) home page: http://www.networkupstools.org/
