#!/bin/sh -e

case "$1" in

  configure)
    if [ -d /etc/udev/rules.d/ ] ; then
        cd /etc/udev/rules.d/
        ln -sf ../nut-usbups.rules 025_nut-usbups.rules
    fi

    # do nothing
    ;;

  abort-upgrade)
    # do nothing
    ;;

  abort-remove)
    # do nothing
    ;;

  abort-deconfigure)
    # do nothing
    ;;

  *)
    echo "$0: incorrect arguments: $*" >&2
    exit 1
    ;;

esac

#DEBHELPER#

exit 0
