#!/bin/sh

set -x
gcc -ggdb -std=c11 -std=gnu99 -Werror -Wall -pedantic -Wc++-compat -D_FORTIFY_SOURCE=2 -O -fstack-protector -I../../include -I../../drivers dmf.c && \
valgrind --leak-check=full ./a.out
