/* network error definitions for consistency */

#define NUT_ERR_ACCESS_DENIED		"ACCESS-DENIED"
#define NUT_ERR_UNKNOWN_UPS		"UNKNOWN-UPS"
#define NUT_ERR_VAR_NOT_SUPPORTED	"VAR-NOT-SUPPORTED"
#define NUT_ERR_CMD_NOT_SUPPORTED	"CMD-NOT-SUPPORTED"
#define NUT_ERR_INVALID_ARGUMENT	"INVALID-ARGUMENT"
#define NUT_ERR_INSTCMD_FAILED		"INSTCMD-FAILED"
#define NUT_ERR_SET_FAILED		"SET-FAILED"
#define NUT_ERR_READONLY		"READONLY"
#define NUT_ERR_TOO_LONG		"TOO-LONG"
#define NUT_ERR_FEATURE_NOT_SUPPORTED	"FEATURE-NOT-SUPPORTED"
#define NUT_ERR_FEATURE_NOT_CONFIGURED	"FEATURE-NOT-CONFIGURED"
#define NUT_ERR_ALREADY_SSL_MODE	"ALREADY-SSL-MODE"

/* errors which are only used by top-level upsd functions */

#define NUT_ERR_DRIVER_NOT_CONNECTED	"DRIVER-NOT-CONNECTED"
#define NUT_ERR_DATA_STALE		"DATA-STALE"
#define NUT_ERR_ALREADY_LOGGED_IN	"ALREADY-LOGGED-IN"
#define NUT_ERR_INVALID_PASSWORD	"INVALID-PASSWORD"
#define NUT_ERR_ALREADY_SET_PASSWORD	"ALREADY-SET-PASSWORD"
#define NUT_ERR_INVALID_USERNAME	"INVALID-USERNAME"
#define NUT_ERR_ALREADY_SET_USERNAME	"ALREADY-SET-USERNAME"
#define NUT_ERR_USERNAME_REQUIRED	"USERNAME-REQUIRED"
#define NUT_ERR_PASSWORD_REQUIRED	"PASSWORD-REQUIRED"
#define NUT_ERR_UNKNOWN_COMMAND		"UNKNOWN-COMMAND"

/* errors which are only used with the old functions */

#define NUT_ERR_VAR_UNKNOWN		"VAR-UNKNOWN"
#define NUT_ERR_UNKNOWN_TYPE		"UNKNOWN-TYPE"
#define NUT_ERR_UNKNOWN_INSTCMD		"UNKNOWN-INSTCMD"
#define NUT_ERR_MISSING_ARGUMENT	"MISSING-ARGUMENT"
#define NUT_ERR_INVALID_VALUE		"INVALID-VALUE"
