#!/bin/sh

# Create group nut

grep -w "nut" /etc/group
if [ $? -eq 1 ]; then
	/usr/sbin/groupadd nut
fi

# Create user for installing "Network UPS Tools"

grep -w "nut" /etc/passwd
if [ $? -eq 1 ]; then
	/usr/sbin/useradd -c "Network UPS Tools" -d /export/home/nut -m nut
fi
