#!/bin/sh

# Create group nut

egrep -i "nut" /etc/group
if [$? -eq 1]; then
	/usr/sbin/groupadd nut

# Create user for installing "Network UPS Tools"

egrep -i "nut" /etc/passwd
if [$? -eq 1]; then
	/usr/sbin/useradd -c "Network UPS Tools" -d /export/home/nut -m nut

# Do nut configuration - here with dummy ups


